
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03_batches.ipynb

from exps.nb_02 import *
import torch.nn.functional as F

def accuracy(out,yb): return ((torch.argmax(out,dim=1)==yb).
                              float().
                              mean())

from torch import optim

class Dataset():
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __len__(self):
        return len(self.x)
    def __getitem__(self,i):
        return self.x[i],self.y[i]

from torch.utils.data import DataLoader,SequentialSampler,RandomSampler

def get_dls(train_ds,valid_ds,bs,**kwargs):
    train_dl = DataLoader(train_ds,bs,shuffle=True,**kwargs)
    valid_dl = DataLoader(valid_ds,bs*2,**kwargs)
    # using pytorch's default DataLoader class
    return train_dl,valid_dl
