
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_propogation.ipynb

from exps.nb_01 import *

datasets_path = "/content/drive/My Drive/fast.ai v3/datasets"
def get_data():
    MNIST_URL='http://deeplearning.net/data/mnist/mnist.pkl'
    path = datasets.download_data(url=MNIST_URL,fname=Path(datasets_path)/'MNIST.gz',ext='.gz')
    with gzip.open(path,'rb') as f:
        ((x_train,y_train),(x_valid,y_valid),_) = pickle.load(f,encoding='latin1')
    return map(tensor,((x_train,y_train,x_valid,y_valid)))

def normalize(x,m,s) : return (x-m)/s
# m,s :: mean,variance rooted

def test_near_zero(a,tol=1e-3) : assert a.abs()<tol,f"Near zero: {a}"

from torch.nn import init

def mse(output,target):
    return (output.squeeze(-1) - target).pow(2).mean()

from torch import nn
